### PR TITLE
Change VertSplit to match StatusLineNc.

### PR DESCRIPTION
**Pull request by mattsoutherden**
For consistency in split layouts.

Before:

before

After:

after

### CODE REVIEW

**Comment by KeitaNakamura** [comment]
In my case, I can see the broken line that separates the windows as you can see in figure.
I'm not sure why you could not see this line.

screenshot 2017-03-09 02 03 47

**Comment by mattsoutherden** [comment]
Ah! I have fillchars set. Sorry.

If using the pipe characters is your preference, feel free to close the PR. :)

BTW. I really love this theme. Thanks. 👍

**Comment by mattsoutherden** [comment]
...or if you like this vert split option, I can alter the PR to set the FG and BG to the same colour for vertsplit to give the same look.

**Comment by KeitaNakamura** [comment]
I prefer the pipe characters, but it's also fine to add the option for block-type vertsplit.
I feel free to merge your PR. Thank you.

**Comment by mattsoutherden** [comment]
Cool. I'll alter the PR to add it as a configurable option then. :)

**Comment by KeitaNakamura** [comment]
Okey. Thank you. :)
I'll close this PR.

**Pull request closed without merging**
